services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_customer_form
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8000:80"
    networks:
      - laravel
    environment:
      - APP_ENV=production
      - APP_DEBUG=false


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel123
    networks:
      - laravel

networks:
  laravel:
    driver: bridge