version: '3.8'
services:
  backend-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    depends_on:
      - backend-db
    ports:
      - "8080:8080"
    networks:
      - appnet

  backend-db:
    image: postgres:15
    environment:
      POSTGRES_DB: bookingtogo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - backend-db-data:/var/lib/postgresql/data
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend-app
    ports:
      - "8000:80"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  backend-db-data: